### ISSUE TITLE
Make MetaCall Protocol as an external dependecy

### ISSUE THREAD

**Issue by viferga** [metacall/chatgpt-functions-deployer#2]
For doing this you can check how metacall/deploy is done.

**Comment by viferga** [comment]
The only thing remaining is to add the new changes in the Durgesh PR to the protocol, publish a new version and link it to the project.

**Comment by durgesh077** [comment]
updated with @metacall/protocol v0.1.25

**Comment by jawad7ali** [comment]
Hi @durgesh077 I want to work in this project please let me know if there's anything for me.

**Comment by durgesh077** [comment]
@jawad7ali it's been closed buddy with pr https://github.com/metacall/protocol/pull/31
