### ISSUE TITLE
Merge Backend into Frontend

### ISSUE THREAD

**Issue by viferga** [metacall/chatgpt-functions-deployer#3]
We should have a unified version only with Frontend code, so we do not store or process anything related to the end user OpenAI key or MetaCall key.

**Comment by durgesh077** [comment]
shifted logic into frontend
- created proxy router to mimic like if it is using express at frontend.
- so I won't had to change much into the code
- created faxios which tries to handled fronted routing
ref: https://github.com/metacall/chatgpt-functions-deployer/tree/master/lambda-deployer-frontend/src/backend_logic

**Comment by viferga** [comment]
So we can delete the backend folder and leave the frontend only?

**Comment by durgesh077** [comment]
Yes
